name: Code Quality
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
jobs:
  test:
    uses: mruoss/action_elixir_run_tests/.github/workflows/elixir-code-quality.yml@v1.3.0
    with:
      checkout: true
      with-kubernetes: true
      check-formatting: true
      run-credo: strict
      run-dialyzer: true
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
