name: Elixir Compatibility Matrix
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
jobs:
  test:
    uses: mruoss/action_elixir_run_tests/.github/workflows/elixir-run-tests.yml@v2.3.3
    with:
      checkout: true
      warnings-as-errors: true
      with-kubernetes: false
      include-integration-tests: false
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
