name: Kubernetes Compatibility Matrix
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
env:
  KUBECONFIG: /home/runner/.kube/config
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # https://hub.docker.com/r/kindest/node/tags
        k8s_version:
          - v1.33.1
          - v1.32.5
          - v1.31.9
          - v1.30.13
    steps:
      - uses: actions/checkout@v7.0.1

      - name: Setup Mise JDX
        id: mise
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/share/mise/bin" >> $GITHUB_PATH
          echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH
          echo "eval \"\$(mise activate bash)\"" >> ~/.bash_profile
          mise install erlang elixir
          echo "otp-version=$(mise current erlang | tr -d '\n')" >> "$GITHUB_OUTPUT"
          echo "elixir-version=$(mise current elixir | tr -d '\n')" >> "$GITHUB_OUTPUT"

      - name: Setup Kubernetes (Kind)
        id: kind
        run: |
          mise install kind
          kind create cluster --image kindest/node:${{ matrix.k8s_version }}

      - name: Retrieve Build Cache
        uses: actions/cache@v6
        id: build-folder-cache
        with:
          path: _build
          key: ${{ runner.os }}-${{ steps.mise.outputs.elixir-version }}-${{ steps.mise.outputs.otp-version }}-build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Retrieve Mix Dependencies Cache
        uses: actions/cache@v6
        id: mix-cache
        with:
          path: deps
          key: ${{ runner.os }}-${{ steps.mise.outputs.elixir-version }}-${{ steps.mise.outputs.otp-version }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - run: mise exec elixir erlang -- mix local.rebar --force
      - run: mise exec elixir erlang -- mix local.hex --force
      - run: mise exec elixir erlang -- mix deps.get
      - run: mise exec elixir erlang -- mix compile --warnings-as-errors
      - run: TEST_WAIT_TIMEOUT=110 mise exec elixir erlang -- mix test --timeout 120000 --only integration --max-failures 1
